### ISSUE TITLE
Lab 3, Part 5, productmanager-v7.sh is missing

### ISSUE THREAD

**Issue by ingo** [aws-samples/aws-saas-factory-bootcamp#19]
Lab3/Part5/scripts/productmanager-v7.sh does not exist.

**Comment by brtrvn** [comment]
The correct name of the script is `product-manager-v7.sh`. The new documentation for Lab 3 in markdown format will be merged to master at the next release.

**Comment by brtrvn** [comment]
Resolved in v1.1
