### ISSUE TITLE
Is there a guide to go with this repository?

### ISSUE THREAD

**Issue by sakopov** [aws-samples/aws-saas-factory-bootcamp#2]
Hi, I know this repository *just* got created, but I was wondering if there is a planned session that will be covering items in this repository or if there is something that's already available? Looks very interesting & thanks for publishing this!

EDIT: Sorry, just read about SaaS Factory program at AWS.

**Comment by judahb** [comment]
This Bootcamp goes live Monday, but Repo needed to go live prior as Cloud9 needs repo to be public to source without SSH key. Lab Guides will be uploaded next week.

**Comment by judahb** [comment]
Lab Guides have been uploaded.

**Comment by brtrvn** [comment]
Detailed guides are available for all 3 labs.
