### ISSUE TITLE
Lab 2, Part 1, Step 7, DynamoDB table: product 

### ISSUE THREAD

**Issue by mariain** [aws-samples/aws-saas-factory-bootcamp#20]
DynamoDB table: product is never being used. Documentation should not ask user to create the table manually.

**Comment by brtrvn** [comment]
This was probably a typo in the table name. The table should be named "ProductBootcamp" and we use it in the subsequent step to `POST` a new product via the ProductManagerService.

The documentation has been updated in the new Lab2.md format. Will be merged to master for the next release.

**Comment by brtrvn** [comment]
Resolved in v1.1
