### ISSUE TITLE
Lab 1 Step 6 image placement

### ISSUE THREAD

**Issue by muellerk22** [aws-samples/aws-saas-factory-bootcamp#24]
The image for the "Do You want to add custom attributes?" is at the top of the page.  However, there is a sentence that states "Your screen should appear as follows:" with nothing below it.  It appears the image at the top of the page should be below that last sentence.

**Comment by brtrvn** [comment]
Resolved in updated Lab1.md version of the docs. Will be merged to master for next release.

**Comment by brtrvn** [comment]
Resolved in v1.1
