### ISSUE TITLE
Lab 1 - Step 6 no export names PUBLICSUBNET1 found

### ISSUE THREAD

**Issue by muellerk22** [aws-samples/aws-saas-factory-bootcamp#26]
I'm looking for advice on how to get past the below in Lab 1 Part 2 - Deploy the user Management Microservice.

```
17:21:55 UTC-0500 | CREATE_FAILED | AWS::CloudFormation::Stack | DevEnvironment | Embedded stack arn:aws:cloudformation:us-east-2:915842112807:stack/UserManagerService-DevEnvironment-1T0U35TGL2RVK/1a359160-99c7-11e8-9afa-060ae44bf6ec was not successfully created: No export named module-saas-bootcamp-base-PUBLICSUBNET1 found
-- | -- | -- | -- | --
```

I did start Part 2 a day after finishing Part 1 if that help anything.  The Cloud Formation Manager still have green status of the services running.  

Thanks

**Comment by judahb** [comment]
Did you follow the troubleshooting guide, and ensure that the Stack Names matched what was provided in the Lab Guides?

Judah Bernstein
Partner Solutions Architect
AWS Partner Program
Amazon Web Services

E:  judahb@amazon.com
P: +1 206 646 2079
C: +1 310 990 4811

          [/Users/judahb/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1511897436]
[id:image002.png@01D39944.10800E90][id:image003.png@01D39944.10800E90][id:image004.png@01D39944.10800E90]
[id:image005.png@01D39944.10800E90][id:image006.png@01D39944.10800E90][id:image007.png@01D39944.10800E90]

**Comment by muellerk22** [comment]
Hi Judah,
I was worried about the names and reviewed them.  I found the trouble shooting guide in the FAQ.  Thanks!

I'm reviewing the guide and there might be a conflict.  
In the Lab0 step 6 says the name is “module-saas-bootcamp-base”
![screen shot 2018-08-08 at 6 45 33 pm](https://user-images.githubusercontent.com/23227137/43870057-434e7e34-9b3b-11e8-92f6-5fcd3ebdba44.jpg)

In the trouble shooting guide it states the name as “module-saas-bootcamp-base**line
![screen shot 2018-08-08 at 6 47 44 pm](https://user-images.githubusercontent.com/23227137/43870115-8f1c2046-9b3b-11e8-9681-f679564de880.jpg)
**”

I tore everything down and re-created with the "baseline"  This failed with:

> No export named module-saas-bootcamp-baseline-TEMPLATEBUCKET found. Rollback requested by user.
--

I'll try again soon.

**Comment by brtrvn** [comment]
If any nested stack fails, the outputs from the parent stack are not available.
`saas-bootcamp-baseline-master.template` exports **PUBLICSUBNET1** but `saas-bootcamp-baseline.template` exports **PublicSubnet1ID**.

In v1.1, Part 6 of Lab 1 is deployed as part of the baseline. The `dev-environment.template` imports have been updated to use **PublicSubnect1ID** to determine where to deploy the EC2 instance for Cloud9.
