### ISSUE TITLE
Move PDFs to Markdown or other format

### ISSUE THREAD

**Issue by ingo** [aws-samples/aws-saas-factory-bootcamp#3]
It's complicated to reference specific parts of the PDF, and impossible to create pull requests. Suggest moving them to some format that would allow easier contributions.

**Comment by judahb** [comment]
This is going to be converted to MD within the next couple weeks.

**Comment by muellerk22** [comment]
MD would be nice.
The format also make it tough to cut and paste from the document to the AWS console.  As an example, Lab 1 Step 9 to customize the invitation messages, it asks to change the message text.  The text is imbedded in an image making it impossible to cut the language and paste in the console.  Being able to do this will provide less friction to the customer IMHO.

**Comment by brtrvn** [comment]
Resolved with v1.1
