### ISSUE TITLE
It needs to be noted that this is not completely secure as its using system not tenant creds. This is intended but should be verified

### ISSUE THREAD

**Issue by judahb** [aws-samples/aws-saas-factory-bootcamp#36]
https://github.com/aws-samples/aws-saas-factory-bootcamp/blob/ab01f04b2e143b03399ccc875e826c21c662e320/Lab2/Part4/app/source/product-manager/src/server.js#L127

**Comment by brtrvn** [comment]
The never finished part 4 of lab 2 was removed in March of 2020 at f104906dfa4bfa37c57047c6af9eea077eae4aa1
