### ISSUE TITLE
Cannot find SAASBOOTCAMPIDE to launch using Cloud9

### ISSUE THREAD

**Issue by derektumulak** [aws-samples/aws-saas-factory-bootcamp#38]
The documentation for lab 1 indicates that the IDE is already provisioned. How would one proceed with the lab if the IDE isn't already there?

Thanks,
-Derek

**Comment by cmjchrisjones** [comment]
+1

**Comment by judahb** [comment]
At the current time, this workshop/bootcamp is run by AWS in a specific engine that is managed by us in events such as Re:Invent, Summits, or AWS SaaS Factory managed events so we can create "burner accounts". We will be discussing if we want to perform the work effort required to externalize the aspect of the pre-provisioning of this workshop/bootcamp and will respond to this thread when we have decided.

**Comment by yairbloom** [comment]
Is it possible to guide us on how to set up this environment locally?

**Comment by grelaxus** [comment]
+1
I probably can get along without the IDE for the LAB 1, but there are no EC2 and ELB available, which mentioned in step 4 of part 2 of lab1

**Comment by jupitercow** [comment]
This got me past the first the hurdle, and allowed me to start creating users at the `user/create` endpoint. This assumes a few things. You need to have node.js and npm running. You may need some other aws tools installed like `aws-cli`. This is definitely not a great place for beginners to jump in.

1. Grab this repo from Github and change directory into the newly downloaded repo
1. Navigate to the user-manager app in the downloaded files: `cd Lab1/Part2/app/source/user-manager/`
1. You will need to add your region to `./shared-modules/config-helper/config/default.json` on line 6, eg: `"region": "us-east-1"`
1. Run the install script: `./local-install.sh`
1. You are now running the server at [http://localhost:3001](http://localhost:3001), so send your `POST` request to [http://localhost:3001/user/create](http://localhost:3001/user/create),

Now you can run the curl command:

```
curl --location --request POST 'http://localhost:3001/user/create' \
--header 'Content-Type: application/json' \
--data-raw '{
    "userPoolId": "us-east-1_YOURPOOLID",
    "tenant_id": "999",
    "userName": "test@test.com",
    "email": "test@test.com",
    "firstName": "Test",
    "lastName": "User",
    "role": "tenantAdmin",
    "tier": "Advanced"
}'
```

**Comment by benjammartin** [comment]
> At the current time, this workshop/bootcamp is run by AWS in a specific engine that is managed by us in events such as Re:Invent, Summits, or AWS SaaS Factory managed events so we can create "burner accounts". We will be discussing if we want to perform the work effort required to externalize the aspect of the pre-provisioning of this workshop/bootcamp and will respond to this thread when we have decided.

Any news about that? Thx.

**Comment by judahb** [comment]
@brtrvn to respond to these issues.

**Comment by brtrvn** [comment]
The new version of the bootcamp workshop can now be run in your own AWS account. We are still finishing the updates to the lab guide documentation. To run the experience on your own, launch the workshop.yml CloudFormation template from the resources folder and follow the lab guides.

**Comment by yairbloom** [comment]
many thanks
