### ISSUE TITLE
Some scripts strongly depends on the aws account environment.

### ISSUE THREAD

**Issue by Blue-Pix** [aws-samples/aws-saas-factory-bootcamp#49]
For brand-new account is ok.
But if the account has even one cloudformation stack, some scripts don't work.

The architecture consists of a lot of nested stack and detect root stack name as `BASELINE_STACK` by referencing to the oldest stack based on CreationTime.

https://github.com/aws-samples/aws-saas-factory-bootcamp/blob/48bb5a89d5c4b78528537b65c227ab0bb529e357/Lab1/Part3/scripts/tenant-manager.sh#L10

I suggest using other logic not depending on specific account environment.

**Comment by brtrvn** [comment]
This is resolved with the latest version of the bootcamp workshop. Resources needed by the shell scripts will now be pulled from Systems Manager Parameter Store.
