### ISSUE TITLE
Is it possible to deploy this locally using on docker?

### ISSUE THREAD

**Issue by Pranit-Harekar** [aws-samples/aws-saas-factory-bootcamp#51]
Is it possible to deploy this locally on docker instead of on the cloud? Would be nice if we can get the steps to do so

**Comment by brtrvn** [comment]
I'm not sure I understand what your question is. The micro services are docker images. The architecture of this system specifically uses AWS services. You cannot run things like DynamoDB or Cognito locally in a docker image.
