### ISSUE TITLE
Code for Lab 1? 

### ISSUE THREAD

**Issue by s1mrankaur** [aws-samples/aws-saas-factory-bootcamp#53]
I am looking for the codebase for lab1 that will onboard and authenticate tenants and their users. This involves provisioning userpool/identity pool/ custom claims. All of that is pretty important information that is missing here. Where can I find it?

**Comment by brtrvn** [comment]
The purpose of Lab 1 is to walk you through all of the onboarding parts _manually_ so you understand the major moving parts of a SaaS onboarding system. The onboarding code is spread across the Registration, User and Tenant management services.

If you'd like to walk the code, start with the /reg endpoint in the source/tenant-registration/server.js file. You'll see that it orchestrates calls to the User service and the Tenant service.

**Comment by s1mrankaur** [comment]
@brtrvn  Thanks. I see that this lab uses SAM for the configuration of resources. We intend to use serverless.yml. Is there another lab that would have a similar codebase with a serverless YAML file?

**Comment by brtrvn** [comment]
This workshop uses plain CloudFormation templates, not SAM. We do not have any published workshop code that utilizes SAM. There is another SaaS workshop that shows some serverless best practices. Check out https://github.com/aws-samples/aws-saas-factory-serverless-workshop.
