### ISSUE TITLE
Auth manager service failed to start.

### ISSUE THREAD

**Issue by Blue-Pix** [aws-samples/aws-saas-factory-bootcamp#64]
ECS task exited repeatedly with following logs.

```
/usr/src/app/auth-manager/node_modules/node-fetch/src/index.js:9
import http from 'http';
^^^^
SyntaxError: Unexpected identifier
...
```

I guess the root cause is that node-fetch package is referred to latest version.
https://github.com/aws-samples/aws-saas-factory-bootcamp/blob/cf3ddf690cdf1e14e5badc30288b510dd018fb02/source/auth-manager/package.json#L12

Current stable version 3.x requires at letst Node.js 12.20.0, but this service uses 10.x.
https://github.com/node-fetch/node-fetch#installation

**Comment by brtrvn** [comment]
Resolved with merge of PR #65
